Display Owner Record. Closes #52
- Copied over thymeleaf templates from original Spring Framework Pet Clinic demo project

* OwnerController

		@GetMapping("/{ownerId}")
		public ModelAndView showOwner(@PathVariable Long ownerId) {             // Instead of returning a String with the view path in it and injecting the Model via a method argument, you can use the ModelAndView composite object to handle this a different way
			ModelAndView mav = new ModelAndView("owners/detail");
			mav.addObject(ownerService.findById(ownerId));

			return mav;
		}

	* OnwerControllerTest

		@Test
		void showOwner() throws Exception {
			// given
			when(mockOwnerService.findById(anyLong())).thenReturn(Owner.builder().build());

			// when
			mockMvc.perform(get("/owners/1"))
			.andExpect(status().isOk())
			.andExpect(model().attribute("owner", equalTo(expectedOwner)))
			.andExpect(view().name("owners/detail"));

			// then
		}

		PLEASE NOTE: Should you forget to mock the ownerService call, the result of that will be null and the addObject method of ModelAndView class has a null check built in, which will result in this error:

			org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalArgumentException: Model object must not be null

				at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
				at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
				at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
				at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
				at org.springframework.test.web.servlet.TestDispatcherServlet.service(TestDispatcherServlet.java:72)
				at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
				at org.springframework.mock.web.MockFilterChain$ServletFilterProxy.doFilter(MockFilterChain.java:167)
				at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:134)
				at org.springframework.test.web.servlet.MockMvc.perform(MockMvc.java:183)
				at guru.springframework.sfgpetclinic.controller.OwnerControllerTest.showOwner(OwnerControllerTest.java:71)
				...
				at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
			Caused by: java.lang.IllegalArgumentException: Model object must not be null
				at org.springframework.util.Assert.notNull(Assert.java:201)
				at org.springframework.ui.ModelMap.addAttribute(ModelMap.java:90)
				at org.springframework.web.servlet.ModelAndView.addObject(ModelAndView.java:300)
				at guru.springframework.sfgpetclinic.controller.OwnerController.showOwner(OwnerController.java:40)
				...
				... 72 more

			As you can see in the stacktrace the addObject method also uses the 'addAttribute' method like we normally do :-)