Add ability to add or update a Pet. Closes #56.
	ERROR: Field error in object 'petDTO' on field 'birthDate': rejected value [2008-06-09]; codes [typeMismatch.petDTO.birthDate,typeMismatch.birthDate,typeMismatch.java.time.LocalDate,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [petDTO.birthDate,birthDate]; arguments []; default message [birthDate]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'java.time.LocalDate' for property 'birthDate'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [java.time.LocalDate] for value '2008-06-09'; nested exception is java.lang.IllegalArgumentException: Parse attempt failed for value [2008-06-09]]
		So similar to the problem with the petType where we couldn't just use the name String to associate a petType to the Pet, here the date string value coming from the web layer doesn't match the LocalDate type in the PetDTO.

	SOLUTION: In the PetDTO annotate the problem property with '@DateTimeFormat(pattern = "yyyy-MM-dd")' to instruct Spring how to parse the date string to a LocalDate value!

		public class PetDTO extends BaseDTO {

			...
			@DateTimeFormat(pattern = "yyyy-MM-dd")
			private LocalDate birthDate;
			...
		}

	Also when debugging there were some StackOverFlow errors where IntelliJ tried to print the current vallue of the Pet or Owner objects.
	This is due to the circular references because of the relationships when called the toString() method.
	So we solved this by explicitly overriding the toString() method ourselves and leaving out the relations.